baseURL = "https://sahilparekh08.github.io/"
title = "Sahil Parekh's Personal Website"
languageCode = "en-us"
theme = "re-terminal"

[params]
  title = "Sahil Parekh"
  owner = "Sahil Parekh"
  keywords = ""
  copyright = ""
  readMore = "Read more"
  description = "Projects, Experience, and Contact Information"
  footer = "© 2024 Sahil Parekh"
  missingContentMessage = "Page not found..."
  missingBackButtonLabel = "Back to home page"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4